use evdev::Key;

use crate::{layout::BasicKey, pointer::PointerButton};

impl BasicKey {
    pub fn glyph(&self) -> String {
        self.label
            .clone()
            .unwrap_or_else(|| default_glyph(&self.key).to_string())
    }
}

impl PointerButton {
    pub fn glyph(&self) -> &'static str {
        match self {
            Self::Left => "′",
            Self::Middle => "″",
            Self::Right => "‴",
        }
    }
}

/// Get a default glyph/character for a key.
fn default_glyph(key: &Key) -> &'static str {
    match *key {
        Key::KEY_ESC => "⎋",
        Key::KEY_1 => "1",
        Key::KEY_2 => "2",
        Key::KEY_3 => "3",
        Key::KEY_4 => "4",
        Key::KEY_5 => "5",
        Key::KEY_6 => "6",
        Key::KEY_7 => "7",
        Key::KEY_8 => "8",
        Key::KEY_9 => "9",
        Key::KEY_0 => "0",
        Key::KEY_MINUS => "-",
        Key::KEY_EQUAL => "=",
        Key::KEY_BACKSPACE => "⌫",
        Key::KEY_TAB => "⇥",
        Key::KEY_Q => "q",
        Key::KEY_W => "w",
        Key::KEY_E => "e",
        Key::KEY_R => "r",
        Key::KEY_T => "t",
        Key::KEY_Y => "y",
        Key::KEY_U => "u",
        Key::KEY_I => "i",
        Key::KEY_O => "o",
        Key::KEY_P => "p",
        Key::KEY_LEFTBRACE => "{",
        Key::KEY_RIGHTBRACE => "}",
        Key::KEY_ENTER => "⏎",
        Key::KEY_LEFTCTRL => "⎈",
        Key::KEY_A => "a",
        Key::KEY_S => "s",
        Key::KEY_D => "d",
        Key::KEY_F => "f",
        Key::KEY_G => "g",
        Key::KEY_H => "h",
        Key::KEY_J => "j",
        Key::KEY_K => "k",
        Key::KEY_L => "l",
        Key::KEY_SEMICOLON => ";",
        Key::KEY_APOSTROPHE => "'",
        Key::KEY_GRAVE => "`",
        Key::KEY_LEFTSHIFT => "⇧",
        Key::KEY_BACKSLASH => "\\",
        Key::KEY_Z => "z",
        Key::KEY_X => "x",
        Key::KEY_C => "c",
        Key::KEY_V => "v",
        Key::KEY_B => "b",
        Key::KEY_N => "n",
        Key::KEY_M => "m",
        Key::KEY_COMMA => ",",
        Key::KEY_DOT => ".",
        Key::KEY_SLASH => "/",
        Key::KEY_RIGHTSHIFT => "⇧",
        Key::KEY_KPASTERISK => "*",
        Key::KEY_LEFTALT => "Alt",
        Key::KEY_SPACE => "␣",
        Key::KEY_CAPSLOCK => "⇪",
        Key::KEY_F1 => "F1",
        Key::KEY_F2 => "F2",
        Key::KEY_F3 => "F3",
        Key::KEY_F4 => "F4",
        Key::KEY_F5 => "F5",
        Key::KEY_F6 => "F6",
        Key::KEY_F7 => "F7",
        Key::KEY_F8 => "F8",
        Key::KEY_F9 => "F9",
        Key::KEY_F10 => "F10",
        Key::KEY_NUMLOCK => "NumLock",
        Key::KEY_SCROLLLOCK => "ScrollLock",
        Key::KEY_KP7 => "7",
        Key::KEY_KP8 => "8",
        Key::KEY_KP9 => "9",
        Key::KEY_KPMINUS => "-",
        Key::KEY_KP4 => "4",
        Key::KEY_KP5 => "5",
        Key::KEY_KP6 => "6",
        Key::KEY_KPPLUS => "+",
        Key::KEY_KP1 => "1",
        Key::KEY_KP2 => "2",
        Key::KEY_KP3 => "3",
        Key::KEY_KP0 => "4",
        Key::KEY_KPDOT => ".",
        Key::KEY_ZENKAKUHANKAKU => "?",
        Key::KEY_102ND => "?",
        Key::KEY_F11 => "F11",
        Key::KEY_F12 => "F12",
        Key::KEY_RO => "?",
        Key::KEY_KATAKANA => "?",
        Key::KEY_HIRAGANA => "?",
        Key::KEY_HENKAN => "?",
        Key::KEY_KATAKANAHIRAGANA => "?",
        Key::KEY_MUHENKAN => "?",
        Key::KEY_KPJPCOMMA => "?",
        Key::KEY_KPENTER => "?",
        Key::KEY_RIGHTCTRL => "?",
        Key::KEY_KPSLASH => "?",
        Key::KEY_SYSRQ => "?",
        Key::KEY_RIGHTALT => "?",
        Key::KEY_LINEFEED => "?",
        Key::KEY_HOME => "?",
        Key::KEY_UP => "↑",
        Key::KEY_PAGEUP => "?",
        Key::KEY_LEFT => "←",
        Key::KEY_RIGHT => "→",
        Key::KEY_END => "?",
        Key::KEY_DOWN => "↓",
        Key::KEY_PAGEDOWN => "?",
        Key::KEY_INSERT => "?",
        Key::KEY_DELETE => "?",
        Key::KEY_MACRO => "?",
        Key::KEY_MUTE => "?",
        Key::KEY_VOLUMEDOWN => "?",
        Key::KEY_VOLUMEUP => "?",
        Key::KEY_POWER => "?", /* SC System Power Down */
        Key::KEY_KPEQUAL => "?",
        Key::KEY_KPPLUSMINUS => "?",
        Key::KEY_PAUSE => "?",
        Key::KEY_SCALE => "?", /* AL Compiz Scale (Expose) */
        Key::KEY_KPCOMMA => "?",
        Key::KEY_HANGEUL => "?",
        Key::KEY_HANJA => "?",
        Key::KEY_YEN => "?",
        Key::KEY_LEFTMETA => "?",
        Key::KEY_RIGHTMETA => "?",
        Key::KEY_COMPOSE => "?",
        Key::KEY_STOP => "?", /* AC Stop */
        Key::KEY_AGAIN => "?",
        Key::KEY_PROPS => "?", /* AC Properties */
        Key::KEY_UNDO => "?",  /* AC Undo */
        Key::KEY_FRONT => "?",
        Key::KEY_COPY => "?",  /* AC Copy */
        Key::KEY_OPEN => "?",  /* AC Open */
        Key::KEY_PASTE => "?", /* AC Paste */
        Key::KEY_FIND => "?",  /* AC Search */
        Key::KEY_CUT => "?",   /* AC Cut */
        Key::KEY_HELP => "?",  /* AL Integrated Help Center */
        Key::KEY_MENU => "?",  /* Menu (show menu) */
        Key::KEY_CALC => "?",  /* AL Calculator */
        Key::KEY_SETUP => "?",
        Key::KEY_SLEEP => "?",  /* SC System Sleep */
        Key::KEY_WAKEUP => "?", /* System Wake Up */
        Key::KEY_FILE => "?",   /* AL Local Machine Browser */
        Key::KEY_SENDFILE => "?",
        Key::KEY_DELETEFILE => "?",
        Key::KEY_XFER => "?",
        Key::KEY_PROG1 => "?",
        Key::KEY_PROG2 => "?",
        Key::KEY_WWW => "?", /* AL Internet Browser */
        Key::KEY_MSDOS => "?",
        Key::KEY_COFFEE => "?", /* AL Terminal Lock/Screensaver */
        Key::KEY_DIRECTION => "?",
        Key::KEY_CYCLEWINDOWS => "?",
        Key::KEY_MAIL => "?",
        Key::KEY_BOOKMARKS => "?", /* AC Bookmarks */
        Key::KEY_COMPUTER => "?",
        Key::KEY_BACK => "?",    /* AC Back */
        Key::KEY_FORWARD => "?", /* AC Forward */
        Key::KEY_CLOSECD => "?",
        Key::KEY_EJECTCD => "?",
        Key::KEY_EJECTCLOSECD => "?",
        Key::KEY_NEXTSONG => "?",
        Key::KEY_PLAYPAUSE => "?",
        Key::KEY_PREVIOUSSONG => "?",
        Key::KEY_STOPCD => "?",
        Key::KEY_RECORD => "?",
        Key::KEY_REWIND => "?",
        Key::KEY_PHONE => "?", /* Media Select Telephone */
        Key::KEY_ISO => "?",
        Key::KEY_CONFIG => "?",   /* AL Consumer Control Configuration */
        Key::KEY_HOMEPAGE => "?", /* AC Home */
        Key::KEY_REFRESH => "?",  /* AC Refresh */
        Key::KEY_EXIT => "?",     /* AC Exit */
        Key::KEY_MOVE => "?",
        Key::KEY_EDIT => "?",
        Key::KEY_SCROLLUP => "?",
        Key::KEY_SCROLLDOWN => "?",
        Key::KEY_KPLEFTPAREN => "?",
        Key::KEY_KPRIGHTPAREN => "?",
        Key::KEY_NEW => "?",  /* AC New */
        Key::KEY_REDO => "?", /* AC Redo/Repeat */
        Key::KEY_F13 => "?",
        Key::KEY_F14 => "?",
        Key::KEY_F15 => "?",
        Key::KEY_F16 => "?",
        Key::KEY_F17 => "?",
        Key::KEY_F18 => "?",
        Key::KEY_F19 => "?",
        Key::KEY_F20 => "?",
        Key::KEY_F21 => "?",
        Key::KEY_F22 => "?",
        Key::KEY_F23 => "?",
        Key::KEY_F24 => "?",
        Key::KEY_PLAYCD => "?",
        Key::KEY_PAUSECD => "?",
        Key::KEY_PROG3 => "?",
        Key::KEY_PROG4 => "?",
        Key::KEY_DASHBOARD => "?", /* AL Dashboard */
        Key::KEY_SUSPEND => "?",
        Key::KEY_CLOSE => "?", /* AC Close */
        Key::KEY_PLAY => "?",
        Key::KEY_FASTFORWARD => "?",
        Key::KEY_BASSBOOST => "?",
        Key::KEY_PRINT => "?", /* AC Print */
        Key::KEY_HP => "?",
        Key::KEY_CAMERA => "?",
        Key::KEY_SOUND => "?",
        Key::KEY_QUESTION => "?",
        Key::KEY_EMAIL => "?",
        Key::KEY_CHAT => "?",
        Key::KEY_SEARCH => "?",
        Key::KEY_CONNECT => "?",
        Key::KEY_FINANCE => "?",
        Key::KEY_SPORT => "?",
        Key::KEY_SHOP => "?",
        Key::KEY_ALTERASE => "?",
        Key::KEY_CANCEL => "?",
        Key::KEY_BRIGHTNESSDOWN => "?",
        Key::KEY_BRIGHTNESSUP => "?",
        Key::KEY_MEDIA => "?",
        Key::KEY_SWITCHVIDEOMODE => "?",
        Key::KEY_KBDILLUMTOGGLE => "?",
        Key::KEY_KBDILLUMDOWN => "?",
        Key::KEY_KBDILLUMUP => "?",
        Key::KEY_SEND => "?",
        Key::KEY_REPLY => "?",
        Key::KEY_FORWARDMAIL => "?",
        Key::KEY_SAVE => "?",
        Key::KEY_DOCUMENTS => "?",
        Key::KEY_BATTERY => "?",
        Key::KEY_BLUETOOTH => "?",
        Key::KEY_WLAN => "?",
        Key::KEY_UWB => "?",
        Key::KEY_UNKNOWN => "?",
        Key::KEY_VIDEO_NEXT => "?",
        Key::KEY_VIDEO_PREV => "?",
        Key::KEY_BRIGHTNESS_CYCLE => "?",
        Key::KEY_BRIGHTNESS_AUTO => "?",
        Key::KEY_DISPLAY_OFF => "?",
        Key::KEY_WWAN => "?",
        Key::KEY_RFKILL => "?",
        Key::KEY_MICMUTE => "?",
        Key::BTN_0 => "?",
        Key::BTN_1 => "?",
        Key::BTN_2 => "?",
        Key::BTN_3 => "?",
        Key::BTN_4 => "?",
        Key::BTN_5 => "?",
        Key::BTN_6 => "?",
        Key::BTN_7 => "?",
        Key::BTN_8 => "?",
        Key::BTN_9 => "?",
        Key::BTN_LEFT => "?",
        Key::BTN_RIGHT => "?",
        Key::BTN_MIDDLE => "?",
        Key::BTN_SIDE => "?",
        Key::BTN_EXTRA => "?",
        Key::BTN_FORWARD => "?",
        Key::BTN_BACK => "?",
        Key::BTN_TASK => "?",
        Key::BTN_TRIGGER => "?",
        Key::BTN_THUMB => "?",
        Key::BTN_THUMB2 => "?",
        Key::BTN_TOP => "?",
        Key::BTN_TOP2 => "?",
        Key::BTN_PINKIE => "?",
        Key::BTN_BASE => "?",
        Key::BTN_BASE2 => "?",
        Key::BTN_BASE3 => "?",
        Key::BTN_BASE4 => "?",
        Key::BTN_BASE5 => "?",
        Key::BTN_BASE6 => "?",
        Key::BTN_DEAD => "?",
        Key::BTN_SOUTH => "?",
        Key::BTN_EAST => "?",
        Key::BTN_C => "?",
        Key::BTN_NORTH => "?",
        Key::BTN_WEST => "?",
        Key::BTN_Z => "?",
        Key::BTN_TL => "?",
        Key::BTN_TR => "?",
        Key::BTN_TL2 => "?",
        Key::BTN_TR2 => "?",
        Key::BTN_SELECT => "?",
        Key::BTN_START => "?",
        Key::BTN_MODE => "?",
        Key::BTN_THUMBL => "?",
        Key::BTN_THUMBR => "?",
        Key::BTN_TOOL_PEN => "?",
        Key::BTN_TOOL_RUBBER => "?",
        Key::BTN_TOOL_BRUSH => "?",
        Key::BTN_TOOL_PENCIL => "?",
        Key::BTN_TOOL_AIRBRUSH => "?",
        Key::BTN_TOOL_FINGER => "?",
        Key::BTN_TOOL_MOUSE => "?",
        Key::BTN_TOOL_LENS => "?",
        Key::BTN_TOOL_QUINTTAP => "?", /* Five fingers on trackpad */
        Key::BTN_TOUCH => "?",
        Key::BTN_STYLUS => "?",
        Key::BTN_STYLUS2 => "?",
        Key::BTN_TOOL_DOUBLETAP => "?",
        Key::BTN_TOOL_TRIPLETAP => "?",
        Key::BTN_TOOL_QUADTAP => "?", /* Four fingers on trackpad */
        Key::BTN_GEAR_DOWN => "?",
        Key::BTN_GEAR_UP => "?",
        Key::KEY_OK => "?",
        Key::KEY_SELECT => "?",
        Key::KEY_GOTO => "?",
        Key::KEY_CLEAR => "?",
        Key::KEY_POWER2 => "?",
        Key::KEY_OPTION => "?",
        Key::KEY_INFO => "?", /* AL OEM Features/Tips/Tutorial */
        Key::KEY_TIME => "?",
        Key::KEY_VENDOR => "?",
        Key::KEY_ARCHIVE => "?",
        Key::KEY_PROGRAM => "?", /* Media Select Program Guide */
        Key::KEY_CHANNEL => "?",
        Key::KEY_FAVORITES => "?",
        Key::KEY_EPG => "?",
        Key::KEY_PVR => "?", /* Media Select Home */
        Key::KEY_MHP => "?",
        Key::KEY_LANGUAGE => "?",
        Key::KEY_TITLE => "?",
        Key::KEY_SUBTITLE => "?",
        Key::KEY_ANGLE => "?",
        Key::KEY_ZOOM => "?",
        Key::KEY_MODE => "?",
        Key::KEY_KEYBOARD => "?",
        Key::KEY_SCREEN => "?",
        Key::KEY_PC => "?",   /* Media Select Computer */
        Key::KEY_TV => "?",   /* Media Select TV */
        Key::KEY_TV2 => "?",  /* Media Select Cable */
        Key::KEY_VCR => "?",  /* Media Select VCR */
        Key::KEY_VCR2 => "?", /* VCR Plus */
        Key::KEY_SAT => "?",  /* Media Select Satellite */
        Key::KEY_SAT2 => "?",
        Key::KEY_CD => "?",   /* Media Select CD */
        Key::KEY_TAPE => "?", /* Media Select Tape */
        Key::KEY_RADIO => "?",
        Key::KEY_TUNER => "?", /* Media Select Tuner */
        Key::KEY_PLAYER => "?",
        Key::KEY_TEXT => "?",
        Key::KEY_DVD => "?", /* Media Select DVD */
        Key::KEY_AUX => "?",
        Key::KEY_MP3 => "?",
        Key::KEY_AUDIO => "?", /* AL Audio Browser */
        Key::KEY_VIDEO => "?", /* AL Movie Browser */
        Key::KEY_DIRECTORY => "?",
        Key::KEY_LIST => "?",
        Key::KEY_MEMO => "?", /* Media Select Messages */
        Key::KEY_CALENDAR => "?",
        Key::KEY_RED => "?",
        Key::KEY_GREEN => "?",
        Key::KEY_YELLOW => "?",
        Key::KEY_BLUE => "?",
        Key::KEY_CHANNELUP => "?",   /* Channel Increment */
        Key::KEY_CHANNELDOWN => "?", /* Channel Decrement */
        Key::KEY_FIRST => "?",
        Key::KEY_LAST => "?", /* Recall Last */
        Key::KEY_AB => "?",
        Key::KEY_NEXT => "?",
        Key::KEY_RESTART => "?",
        Key::KEY_SLOW => "?",
        Key::KEY_SHUFFLE => "?",
        Key::KEY_BREAK => "?",
        Key::KEY_PREVIOUS => "?",
        Key::KEY_DIGITS => "?",
        Key::KEY_TEEN => "?",
        Key::KEY_TWEN => "?",
        Key::KEY_VIDEOPHONE => "?",     /* Media Select Video Phone */
        Key::KEY_GAMES => "?",          /* Media Select Games */
        Key::KEY_ZOOMIN => "?",         /* AC Zoom In */
        Key::KEY_ZOOMOUT => "?",        /* AC Zoom Out */
        Key::KEY_ZOOMRESET => "?",      /* AC Zoom */
        Key::KEY_WORDPROCESSOR => "?",  /* AL Word Processor */
        Key::KEY_EDITOR => "?",         /* AL Text Editor */
        Key::KEY_SPREADSHEET => "?",    /* AL Spreadsheet */
        Key::KEY_GRAPHICSEDITOR => "?", /* AL Graphics Editor */
        Key::KEY_PRESENTATION => "?",   /* AL Presentation App */
        Key::KEY_DATABASE => "?",       /* AL Database App */
        Key::KEY_NEWS => "?",           /* AL Newsreader */
        Key::KEY_VOICEMAIL => "?",      /* AL Voicemail */
        Key::KEY_ADDRESSBOOK => "?",    /* AL Contacts/Address Book */
        Key::KEY_MESSENGER => "?",      /* AL Instant Messaging */
        Key::KEY_DISPLAYTOGGLE => "?",  /* Turn display (LCD) on and off */
        Key::KEY_SPELLCHECK => "?",     /* AL Spell Check */
        Key::KEY_LOGOFF => "?",         /* AL Logoff */
        Key::KEY_DOLLAR => "?",
        Key::KEY_EURO => "?",
        Key::KEY_FRAMEBACK => "?", /* Consumer - transport controls */
        Key::KEY_FRAMEFORWARD => "?",
        Key::KEY_CONTEXT_MENU => "?", /* GenDesc - system context menu */
        Key::KEY_MEDIA_REPEAT => "?", /* Consumer - transport control */
        Key::KEY_10CHANNELSUP => "?", /* 10 channels up (10+) */
        Key::KEY_10CHANNELSDOWN => "?", /* 10 channels down (10-) */
        Key::KEY_IMAGES => "?",       /* AL Image Browser */
        Key::KEY_DEL_EOL => "?",
        Key::KEY_DEL_EOS => "?",
        Key::KEY_INS_LINE => "?",
        Key::KEY_DEL_LINE => "?",
        Key::KEY_FN => "?",
        Key::KEY_FN_ESC => "?",
        Key::KEY_FN_F1 => "?",
        Key::KEY_FN_F2 => "?",
        Key::KEY_FN_F3 => "?",
        Key::KEY_FN_F4 => "?",
        Key::KEY_FN_F5 => "?",
        Key::KEY_FN_F6 => "?",
        Key::KEY_FN_F7 => "?",
        Key::KEY_FN_F8 => "?",
        Key::KEY_FN_F9 => "?",
        Key::KEY_FN_F10 => "?",
        Key::KEY_FN_F11 => "?",
        Key::KEY_FN_F12 => "?",
        Key::KEY_FN_1 => "?",
        Key::KEY_FN_2 => "?",
        Key::KEY_FN_D => "?",
        Key::KEY_FN_E => "?",
        Key::KEY_FN_F => "?",
        Key::KEY_FN_S => "?",
        Key::KEY_FN_B => "?",
        Key::KEY_BRL_DOT1 => "?",
        Key::KEY_BRL_DOT2 => "?",
        Key::KEY_BRL_DOT3 => "?",
        Key::KEY_BRL_DOT4 => "?",
        Key::KEY_BRL_DOT5 => "?",
        Key::KEY_BRL_DOT6 => "?",
        Key::KEY_BRL_DOT7 => "?",
        Key::KEY_BRL_DOT8 => "?",
        Key::KEY_BRL_DOT9 => "?",
        Key::KEY_BRL_DOT10 => "?",
        Key::KEY_NUMERIC_0 => "?", /* used by phones, remote controls, */
        Key::KEY_NUMERIC_1 => "?", /* and other keypads */
        Key::KEY_NUMERIC_2 => "?",
        Key::KEY_NUMERIC_3 => "?",
        Key::KEY_NUMERIC_4 => "?",
        Key::KEY_NUMERIC_5 => "?",
        Key::KEY_NUMERIC_6 => "?",
        Key::KEY_NUMERIC_7 => "?",
        Key::KEY_NUMERIC_8 => "?",
        Key::KEY_NUMERIC_9 => "?",
        Key::KEY_NUMERIC_STAR => "?",
        Key::KEY_NUMERIC_POUND => "?",
        Key::KEY_NUMERIC_A => "?", /* Phone key A - HUT Telephony 0xb9 */
        Key::KEY_NUMERIC_B => "?",
        Key::KEY_NUMERIC_C => "?",
        Key::KEY_NUMERIC_D => "?",
        Key::KEY_CAMERA_FOCUS => "?",
        Key::KEY_WPS_BUTTON => "?",      /* WiFi Protected Setup key */
        Key::KEY_TOUCHPAD_TOGGLE => "?", /* Request switch touchpad on or off */
        Key::KEY_TOUCHPAD_ON => "?",
        Key::KEY_TOUCHPAD_OFF => "?",
        Key::KEY_CAMERA_ZOOMIN => "?",
        Key::KEY_CAMERA_ZOOMOUT => "?",
        Key::KEY_CAMERA_UP => "?",
        Key::KEY_CAMERA_DOWN => "?",
        Key::KEY_CAMERA_LEFT => "?",
        Key::KEY_CAMERA_RIGHT => "?",
        Key::KEY_ATTENDANT_ON => "?",
        Key::KEY_ATTENDANT_OFF => "?",
        Key::KEY_ATTENDANT_TOGGLE => "?", /* Attendant call on or off */
        Key::KEY_LIGHTS_TOGGLE => "?",    /* Reading light on or off */
        Key::BTN_DPAD_UP => "?",
        Key::BTN_DPAD_DOWN => "?",
        Key::BTN_DPAD_LEFT => "?",
        Key::BTN_DPAD_RIGHT => "?",
        Key::KEY_ALS_TOGGLE => "?",   /* Ambient light sensor */
        Key::KEY_BUTTONCONFIG => "?", /* AL Button Configuration */
        Key::KEY_TASKMANAGER => "?",  /* AL Task/Project Manager */
        Key::KEY_JOURNAL => "?",      /* AL Log/Journal/Timecard */
        Key::KEY_CONTROLPANEL => "?", /* AL Control Panel */
        Key::KEY_APPSELECT => "?",    /* AL Select Task/Application */
        Key::KEY_SCREENSAVER => "?",  /* AL Screen Saver */
        Key::KEY_VOICECOMMAND => "?", /* Listening Voice Command */
        Key::KEY_ASSISTANT => "?",
        Key::KEY_KBD_LAYOUT_NEXT => "?",
        Key::KEY_BRIGHTNESS_MIN => "?", /* Set Brightness to Minimum */
        Key::KEY_BRIGHTNESS_MAX => "?", /* Set Brightness to Maximum */
        Key::KEY_KBDINPUTASSIST_PREV => "?",
        Key::KEY_KBDINPUTASSIST_NEXT => "?",
        Key::KEY_KBDINPUTASSIST_PREVGROUP => "?",
        Key::KEY_KBDINPUTASSIST_NEXTGROUP => "?",
        Key::KEY_KBDINPUTASSIST_ACCEPT => "?",
        Key::KEY_KBDINPUTASSIST_CANCEL => "?",
        Key::KEY_RIGHT_UP => "?",
        Key::KEY_RIGHT_DOWN => "?",
        Key::KEY_LEFT_UP => "?",
        Key::KEY_LEFT_DOWN => "?",
        Key::KEY_ROOT_MENU => "?",
        Key::KEY_MEDIA_TOP_MENU => "?",
        Key::KEY_NUMERIC_11 => "?",
        Key::KEY_NUMERIC_12 => "?",
        Key::KEY_AUDIO_DESC => "?",
        Key::KEY_3D_MODE => "?",
        Key::KEY_NEXT_FAVORITE => "?",
        Key::KEY_STOP_RECORD => "?",
        Key::KEY_PAUSE_RECORD => "?",
        Key::KEY_VOD => "?", /* Video on Demand */
        Key::KEY_UNMUTE => "?",
        Key::KEY_FASTREVERSE => "?",
        Key::KEY_SLOWREVERSE => "?",
        Key::KEY_DATA => "?",
        Key::KEY_ONSCREEN_KEYBOARD => "?",
        Key::KEY_PRIVACY_SCREEN_TOGGLE => "?",
        Key::KEY_SELECTIVE_SCREENSHOT => "?",
        Key::BTN_TRIGGER_HAPPY1 => "?",
        Key::BTN_TRIGGER_HAPPY2 => "?",
        Key::BTN_TRIGGER_HAPPY3 => "?",
        Key::BTN_TRIGGER_HAPPY4 => "?",
        Key::BTN_TRIGGER_HAPPY5 => "?",
        Key::BTN_TRIGGER_HAPPY6 => "?",
        Key::BTN_TRIGGER_HAPPY7 => "?",
        Key::BTN_TRIGGER_HAPPY8 => "?",
        Key::BTN_TRIGGER_HAPPY9 => "?",
        Key::BTN_TRIGGER_HAPPY10 => "?",
        Key::BTN_TRIGGER_HAPPY11 => "?",
        Key::BTN_TRIGGER_HAPPY12 => "?",
        Key::BTN_TRIGGER_HAPPY13 => "?",
        Key::BTN_TRIGGER_HAPPY14 => "?",
        Key::BTN_TRIGGER_HAPPY15 => "?",
        Key::BTN_TRIGGER_HAPPY16 => "?",
        Key::BTN_TRIGGER_HAPPY17 => "?",
        Key::BTN_TRIGGER_HAPPY18 => "?",
        Key::BTN_TRIGGER_HAPPY19 => "?",
        Key::BTN_TRIGGER_HAPPY20 => "?",
        Key::BTN_TRIGGER_HAPPY21 => "?",
        Key::BTN_TRIGGER_HAPPY22 => "?",
        Key::BTN_TRIGGER_HAPPY23 => "?",
        Key::BTN_TRIGGER_HAPPY24 => "?",
        Key::BTN_TRIGGER_HAPPY25 => "?",
        Key::BTN_TRIGGER_HAPPY26 => "?",
        Key::BTN_TRIGGER_HAPPY27 => "?",
        Key::BTN_TRIGGER_HAPPY28 => "?",
        Key::BTN_TRIGGER_HAPPY29 => "?",
        Key::BTN_TRIGGER_HAPPY30 => "?",
        Key::BTN_TRIGGER_HAPPY31 => "?",
        Key::BTN_TRIGGER_HAPPY32 => "?",
        Key::BTN_TRIGGER_HAPPY33 => "?",
        Key::BTN_TRIGGER_HAPPY34 => "?",
        Key::BTN_TRIGGER_HAPPY35 => "?",
        Key::BTN_TRIGGER_HAPPY36 => "?",
        Key::BTN_TRIGGER_HAPPY37 => "?",
        Key::BTN_TRIGGER_HAPPY38 => "?",
        Key::BTN_TRIGGER_HAPPY39 => "?",
        Key::BTN_TRIGGER_HAPPY40 => "?",
        _ => "?",
    }
}
